language: ruby
cache: bundler
sudo: false

rvm:
  - '2.0'
  - '2.1'
  - '2.2'

addons:
  postgresql: '9.3'

before_script:
  - psql -c 'create database coupons_test;' -U postgres

env:
  - DATABASE_URL=postgres://postgres@localhost/coupons_test

gemfile:
  - Gemfile
  - gemfiles/rails_4_2.gemfile

addons:
  code_climate:
    repo_token:
      secure: 'iD2QMCQ9RHeaThxeRxkPeTMgLjOZhTXaaBnhFUMMe2CTbmqfWSld/+GPOYECr9VEEjPOyN8lkfTJ1benxa0Wog6xk7DC7aCXjgftpA95OmsJd+9czGv/2pp0D4m6xWGkKgB9IYM3IVhzLqqGeAjxInKgQOjVhKgkaaRYGUYTrFc='
